language: php
php:
  - 5.6
before_script:
  - mysql -e 'create database `dev_protavel`;'
  - cp .env.travis .env
  - composer self-update
  - composer install -n
  - php artisan key:generate
  - php artisan migrate:refresh --seed -n
  # - ./vendor/bin/codecept build
script: 
  #- ./vendor/bin/codecept run
