version: 3.0

stages:
  - 测试阶段
  - 构建阶段
  - 发布阶段

测试任务:
  stage: 测试阶段
  job_type: test
  label: develop
  image: daocloud.io/rodv2/ci-laravel

  services:
    - mysql

  env:
    - DB_HOST = $MYSQL_PORT_3306_TCP_ADDR
    - DB_DATABASE = 'test'
    - DB_USERNAME = 'root'
    - DB_PASSWORD = ''
    - DB_PORT = $MYSQL_PORT_3306_TCP_PORT

  install:
    - pwd
    - env
    - npm install
    - bower install
    - composer self-update
    - composer install -n

  before_script:
    - pwd
    - env | grep 'DB'
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed -n

  script:
    - pwd
    - ./vendor/bin/phpunit

构建任务:
  stage: 构建阶段
  job_type: image_build
  label: release-image
  build_dir: /
  dockerfile_path: /Dockerfile
  cache: true
